version = "1.0"

[homeserver]
name = "Homeserver configuration"
services = ["__APP__"]

    [homeserver.config]
    name = "Configuration options"

        [homeserver.config.async_media]
        ask = "Does the homeserver support https://github.com/matrix-org/matrix-spec-proposals/pull/2246?"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Enables asynchronous media uploads"
        bind = "homeserver>async_media:__FINALPATH__/config.yaml"

[appservice]
name = "Application service configuration"
services = ["__APP__"]

    [appservice.config]
    name = "General configuration"

        [appservice.config.ephemeral_events]
        ask = "Whether or not to receive ephemeral events via appservice transactions"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Requires MSC2409 support (i.e. Synapse 1.22+). You should disable bridge -> sync_with_custom_puppets when this is enabled"
        bind = "appservice>ephemeral_events:__FINALPATH__/config.yaml"

    [appservice.bot]
    name = "Appservice bot configuration"

        [appservice.bot.botname]
        ask = "Username of the appservice bot"
        type = "string"
        help = "Sets bot username. Please keep in mind that the bot admin room for previous bot username will stop working so you may need to create a new one using the new username"

        [appservice.bot.displayname]
        ask = "Display name for bot"
        type = "string"
        help = "Set to 'remove' to remove display name, leave empty to leave display name as-is"

        [appservice.bot.avatar]
        ask = "Avatar for bot"
        type = "string"
        help = "Set to 'remove' to remove avatar, leave empty to leave avatar as-is"

[metrics]
name = "Prometheus configuration"
services = ["__APP__"]

    [metrics.config]
    name = "General configuration"

        [metrics.config.enabled]
        ask = "Enable prometheus metrics"
        type = "boolean"
        yes = "true"
        no = "false"
        bind = "metrics>enabled:__FINALPATH__/config.yaml"

        [metrics.config.listen]
        ask = "IP and port where the metrics listener should be"
        type = "string"
        default = "127.0.0.1:8001"
        help = "The path is always /metrics"
        bind = "metrics>listen:__FINALPATH__/config.yaml"

[whatsapp]
name = "Whatsapp configuration"
help = "Configuration for things that are directly sent to WhatsApp"
services = ["__APP__"]

    [whatsapp.config]
    name = "General configuration"

        [whatsapp.config.os_name]
        ask = "Device name that's shown in the 'WhatsApp Web' section in the mobile app"
        type = "string"
        default = "Mautrix-WhatsApp bridge"
        bind = "whatsapp>os_name:__FINALPATH__/config.yaml"

        [whatsapp.config.browser_name]
        ask = "Browser name that determines the logo shown in the mobile app"
        type = "select"
        choices = ["unknown", "chrome", "firefox", "ie", "opera", "safari", "edge", "desktop", "ipad", "android_tablet", "ohana", "aloha", "catalina", "tcl_tv"]
        default = "unknown"
        help = "Must be 'unknown' for a generic icon or a valid browser name if you want a specific icon"
        bind = "whatsapp>browser_name:__FINALPATH__/config.yaml"

[bridge]
name = "Bridge configuration"
services = ["__APP__"]

    [bridge.config]
    name = "General configuration"

        [bridge.config.username_template]
        ask = "Localpart template of MXIDs for WhatsApp users"
        type = "string"
        default = "whatsapp_{{.}}"
        help = "{{.}} is replaced with the phone number of the WhatsApp user"
        bind = "bridge>username_template:__FINALPATH__/config.yaml"

[encryption]
name = "Encryption"
services = ["__APP__"]
    [encryption.config]
    name = "Encryption settings"

        [encryption.config.encryption]
        ask = "Enable encryption"
        type = "boolean"
        yes = "true"
		no = "false"
        help = "Enables end to bridge encryption"
        bind = "encryption>allow:__FINALPATH__/config.yaml"

        [encryption.config.default_encryption]
        ask = "Default encryption"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Force-enable encryption in all portals the bridge creates. This will cause the bridge bot to be in private chats for the encryption to work properly."
        bind = "encryption>default:__FINALPATH__/config.yaml"

        [encryption.config.require_encryption]
        ask = "Require encryption"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Require encryption, drop any unencrypted messages."
        bind = "encryption>require:__FINALPATH__/config.yaml"

[usermanagement]
name = "User management"
services = ["__APP__"]

    [usermanagement.config]
    name = "User management"

        [usermanagement.config.helptext]
        ask = "Allowed values:\n&emsp;&emsp;* - All Matrix users\n&emsp;&emsp;domain - All users on that homeserver\n&emsp;&emsp;mxid (@user:matrix.org) - Specific Matrix user\n&emsp;&emsp;username - Specific local user"
        type = "markdown"

        [usermanagement.config.listuser]
        ask = "Users"
        type = "tags"
        visible = "role == 'user'"

        [usermanagement.config.listadmin]
        ask = "Admins"
        type = "tags"
        visible = "role == 'admin'"

        [usermanagement.config.listrelay]
        ask = "Relay users"
        type = "tags"
        visible = "role == 'relay'"

        [usermanagement.config.role]
        ask = "Role"
        type = "select"
        choices = ["user", "admin", "relay"]

[privacy]
name = "Privacy"
services = ["__APP__"]

    [privacy.config]
    name = "Privacy settings"

        [privacy.config.delivery_receipts]
        ask = "Delivery receipts"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Should the bridge send a read receipt from the bridge bot when a message has been sent to WhatsApp?"
        bind = "bridge>delivery_receipts:__FINALPATH__/config.yaml"

        [privacy.config.send_presence_on_typing]
        ask = "Send presence on typing"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Send the presence as 'available' to whatsapp when users start typing on a portal."
        bind = "bridge>send_presence_on_typing:__FINALPATH__/config.yaml"

        [privacy.config.url_previews]
        ask = "URL previews"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Should the bridge detect URLs in outgoing messages, ask the homeserver to generate a preview, and send it to WhatsApp?"
        bind = "bridge>url_previews:__FINALPATH__/config.yaml"
